%YAML:1.0

#######################################
# MV-SUA133GC  8mm
exposure    : 1000
rGain       : 159 #139
gGain       : 139 #119
bGain       : 100

analogGain  : 192
gamma       : 100
contrast    : 100

#######################################
# MV-SUA134GC  6mm
# exposure    : 1000

# rGain       : -1
# gGain       : -1
# bGain       : -1

# analogGain  : 6
# gamma       : 50
# contrast    : -1


#################################################
####                                         ####
####             camera intrinsics           ####
####                                         ####
#################################################

# camera intrinsics
# [ fx 0  cx ]
# [ 0  fy cy ]
# [ 0  0  1  ]

# å°å½©çŸ³çš„ä¸Šäº‘å°ğŸ’ğŸ’
å°å½©çŸ³ä¸Šäº‘å°:
    CI: !!opencv-matrix
        rows: 3
        cols: 3
        dt: d
        data: [ 2034.,   0.,       630.,
                0.,      2034.,    484.,
                0.,      0.,       1.     ]
    D : !!opencv-matrix
        rows: 1
        cols: 5
        dt: d
        data: [-0.069185, 0.240646, -0.003035, 0.001489, 0.000000]

# å°å½©çŸ³çš„ä¸‹äº‘å°ğŸ’ğŸ’
å°å½©çŸ³ä¸‹äº‘å°:
    CI: !!opencv-matrix
        rows: 3
        cols: 3
        dt: d
        data: [ 2031.,   0.,       666.,
                0.,      2031.,    477.,
                0.,      0.,       1.     ]
    D : !!opencv-matrix
        rows: 1
        cols: 5
        dt: d
        data: [-0.105423, 0.396354, -0.003637, 0.004282, 0.000000]

# å°èºå·ğŸšğŸš
å°èºå·:
    CI: !!opencv-matrix
        rows: 3
        cols: 3
        dt: d
        data: [ 1775.,   0.,       640.,
                0.,      1775.,    400.,
                0.,      0.,       1.     ]

# å°è·³è›™ğŸ¸ğŸ¸
# å°è·³è›™æ—§ç›¸æœº:
#     CI: !!opencv-matrix
#         rows: 3
#         cols: 3
#         dt: d
#         data: [ 1775.,   0.,       640.,
#                 0.,      1775.,    400.,
#                 0.,      0.,       1.     ]

# ğŸ¸ğŸ¸å•Šè›™çš„æ–°ç›¸æœºMV-SUA133GC
å°è·³è›™:
    CI: !!opencv-matrix
        rows: 3
        cols: 3
        dt: d
        data: [ 2089.,   0.,       637.,
                0.,      2106.,    512.,
                0.,      0.,       1.     ]
    D : !!opencv-matrix
        rows: 1
        cols: 5
        dt: d
        data: [-0.055, 0.277, -0.003, 0, 0]

å°ç‹éœ¸:
    CI: !!opencv-matrix
        rows: 3
        cols: 3
        dt: d
        data: [ 2068.43,   0.,       603.66,
                0.,      2081.9,    503.65,
                0.,      0.,       1.     ]
    D : !!opencv-matrix
        rows: 1
        cols: 5
        dt: d
        data: [-0.067, 0.331, -0.0023, -0.00027, 0]

å°éœ¸ç‹:
    CI: !!opencv-matrix
        rows: 3
        cols: 3
        dt: d
        data: [ 2071.55,   0.,       691.28,
                0.,      2089.07,    498.89,
                0.,      0.,       1.     ]
    D : !!opencv-matrix
        rows: 1
        cols: 5
        dt: d
        data: [-0.083, 0.454, -0.004, 0.000786, 0]
å°æ±¤åœ†:
    CI: !!opencv-matrix
        rows: 3
        cols: 3
        dt: d
        data: [ 1785.51207,   0.,       685.418724,
                0.,      1799.256178,    479.824388,
                0.,      0.,       1.     ]
    D : !!opencv-matrix
        rows: 1
        cols: 5
        dt: d
        data: [-0.070334, 0.42633, -0.003443, -0.005996, 0]

Ghost:
    CI: !!opencv-matrix
        rows: 3
        cols: 3
        dt: d
        data: [ 2102.882885,   0.,       651.267544,
                0.,      2120.096193,    521.351318,
                0.,      0.,       1.     ]
    D : !!opencv-matrix
        rows: 1
        cols: 5
        dt: d
        data: [-0.077815, 0.356568, 0.000806, 0.005844, 0]
# ğŸ”«ğŸ”«å“¨å…µåº•ç›˜USBç›¸æœº1
å°å½©çŸ³åº•ç›˜USBç›¸æœº1:
    CI: !!opencv-matrix
        rows: 3
        cols: 3
        dt: d
        data: [ 1395.0,   0.,       599.5,
                0.,      1394.0,    342.3,
                0.,      0.,       1.     ]
    D : !!opencv-matrix
        rows: 1
        cols: 5
        dt: d
        data: [-0.390179, 0.230717, -0.000888, -0.002189, 0.000000]

# ğŸ”«ğŸ”«å“¨å…µåº•ç›˜USBç›¸æœº2
å°å½©çŸ³åº•ç›˜USBç›¸æœº2:
    CI: !!opencv-matrix
        rows: 3
        cols: 3
        dt: d
        data: [ 1352.6,  0.,       667.4,
                0.,      1354.4,   358.8,
                0.,      0.,       1.     ]
    D : !!opencv-matrix
        rows: 1
        cols: 5
        dt: d
        data: [-0.357403, 0.164756, 0.005814, -0.001768, 0.000000]
